"""
Implementation based on the paper of Rama Cont and Milena Vuletic (2022) to get a simulation of
implied volatility surface paths with static-arbitrage penalisation. The weighted Monte Carlo 
is applied to entire simulated scenarios/paths:

    phi(path_i) = sum_t Phi(sigma_t^i)
    w_i(beta)  = exp(-beta * phi(path_i)) / sum_j exp(-beta * phi(path_j))

The output is sampled from simulated paths generated by the baseline PCA/AR(1) factor model P0.

"""
from __future__ import annotations
from dataclasses import dataclass, field, replace
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.special import ndtr

@dataclass(frozen=True)
class SimulationConfig:
    input_path: Path = Path("data/treated/vol_surface_cube.npz")
    output_path: Path = Path("data/treated/simulated_vol_surface.npz")
    candidate_path_diagnostics_path: Path = Path(
        "data/treated/wmc_candidate_path_diagnostics.csv"
    )
    selected_path_diagnostics_path: Path = Path(
        "data/treated/wmc_selected_path_diagnostics.csv"
    )
    selected_surface_diagnostics_path: Path = Path(
        "data/treated/wmc_selected_surface_diagnostics.csv"
    )

    n_output_paths: int = 10
    path_length: int = 64  # number of surfaces in each path, including t=0
    n_candidate_paths: Optional[int] = None
    candidate_multiplier: int = 500
    candidate_batch_size: int = 512

    n_factors: int = 4
    seed: int = 42
    beta: float = 1.0e4
    shock_scale: float = 1.0

    # Finite beta is the paper's default object. beta going to infinity can be mimicked by requiring zero-penalty paths.
    require_zero_path: bool = True
    surface_arb_tol: float = 1.0e-15
    path_arb_tol: Optional[float] = None

    # The paper's examples start scenarios from an observed initial surface.
    # `last` simulates future scenarios from the latest historical surface.
    # `random_history` is useful for stress testing the unconditional model.
    start_mode: str = "last"  # one of: last, random_history, stationary
    start_index: Optional[int] = None

    # Residual covariance of AR(1) factor innovations.
    # `full` preserves any estimated cross-factor residual dependence;
    # `diag` matches independent factor innovations.
    residual_covariance: str = "full"  # full or diag

    r: float = 0.0
    vol_floor: float = 1.0e-6
    vol_cap: float = 1.0


@dataclass
class SimulationResult:
    paths: np.ndarray
    cube: np.ndarray
    m_grid: np.ndarray
    tenor_days: np.ndarray
    asof_dates: np.ndarray
    selected_candidate_path_indices: np.ndarray
    candidate_path_diagnostics: pd.DataFrame
    selected_path_diagnostics: pd.DataFrame
    selected_surface_diagnostics: pd.DataFrame
    meta: Dict[str, Any] = field(default_factory=dict)


def load_cube_npz(path: str | Path) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, Dict[str, Any]]:
    path = Path(path)
    data = np.load(path, allow_pickle=True)

    cube = np.asarray(data["cube"], dtype=float)
    m_grid = np.asarray(data["m_grid"], dtype=float)
    tenor_days = np.asarray(data["tenor_days"], dtype=float)

    if "asof_dates" in data.files:
        asof_dates = np.asarray(data["asof_dates"])
    else:
        asof_dates = np.arange(cube.shape[2]).astype(str)

    meta: Dict[str, Any] = {}
    if "meta" in data.files:
        try:
            raw = data["meta"]
            meta = raw.item() if getattr(raw, "shape", None) == () else {"raw_meta": raw.tolist()}
        except Exception:
            meta = {"raw_meta": str(data["meta"])}

    if cube.ndim != 3:
        raise ValueError(f"Expected cube with shape (n_m,n_tenor,n_dates), got {cube.shape}")
    if cube.shape[0] != len(m_grid):
        raise ValueError("cube first dimension must match len(m_grid)")
    if cube.shape[1] != len(tenor_days):
        raise ValueError("cube second dimension must match len(tenor_days)")

    return cube, m_grid, tenor_days, asof_dates, meta


def save_result_npz(path: str | Path, result: SimulationResult) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        paths=result.paths,
        cube=result.cube,
        m_grid=result.m_grid,
        tenor_days=result.tenor_days,
        asof_dates=np.asarray(result.asof_dates),
        selected_candidate_path_indices=result.selected_candidate_path_indices,
        meta=np.array(result.meta, dtype=object),
    )


def cube_to_batch_m_t(cube: np.ndarray) -> np.ndarray:
    """(n_m,n_T,n_dates) -> (n_dates,n_m,n_T)."""
    cube = np.asarray(cube, dtype=float)
    if cube.ndim != 3:
        raise ValueError(f"Expected 3D cube, got {cube.shape}")
    return np.moveaxis(cube, 2, 0)


def batch_m_t_to_cube(batch: np.ndarray) -> np.ndarray:
    """(n_dates,n_m,n_T) -> (n_m,n_T,n_dates)."""
    batch = np.asarray(batch, dtype=float)
    if batch.ndim != 3:
        raise ValueError(f"Expected 3D batch, got {batch.shape}")
    return np.moveaxis(batch, 0, 2)


def _to_fraction_vol(x: np.ndarray) -> np.ndarray:
    out = np.asarray(x, dtype=float)
    if np.nanmedian(out) > 2.0:
        out = out / 100.0
    return out


def _from_fraction_vol(x: np.ndarray, output_in_percent: bool) -> np.ndarray:
    return np.asarray(x, dtype=float) * (100.0 if output_in_percent else 1.0)


def _fill_nan_surface_batch(batch: np.ndarray) -> np.ndarray:
    out = np.asarray(batch, dtype=float).copy()
    for k in range(out.shape[0]):
        df = pd.DataFrame(out[k])
        out[k] = (
            df.interpolate(axis=0, limit_direction="both")
            .interpolate(axis=1, limit_direction="both")
            .ffill()
            .bfill()
            .values
        )
    return out



# Static-arbitrage penalty Phi(sigma)
def relative_call_from_iv_batch(
    sigma_frac: np.ndarray,
    m_grid: np.ndarray,
    tau_grid: np.ndarray,
    r: float = 0.0,
) -> np.ndarray:
    """Relative Black-Scholes call prices from IV surfaces.

    sigma_frac: (B,n_m,n_tau) in fraction units.
    Returns C with the same shape.
    """
    sigma = np.clip(np.asarray(sigma_frac, dtype=float), 1.0e-12, None)
    m_grid = np.asarray(m_grid, dtype=float)
    tau_grid = np.asarray(tau_grid, dtype=float)

    if sigma.ndim == 2:
        sigma = sigma[None, :, :]
    if sigma.ndim != 3:
        raise ValueError(f"sigma_frac must be 2D or 3D, got {sigma.shape}")
    if sigma.shape[1:] != (len(m_grid), len(tau_grid)):
        raise ValueError(
            f"Surface shape {sigma.shape[1:]} incompatible with grids "
            f"({len(m_grid)}, {len(tau_grid)})"
        )

    M, T = np.meshgrid(m_grid, tau_grid, indexing="ij")
    T = np.maximum(T, 1.0e-12)
    M = M[None, :, :]
    T = T[None, :, :]

    d1 = (-np.log(M) + T * (float(r) + 0.5 * sigma**2)) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return ndtr(d1) - M * np.exp(-float(r) * T) * ndtr(d2)


def arbitrage_penalties_from_calls_batch(
    C: np.ndarray,
    m_grid: np.ndarray,
    tau_grid: np.ndarray,
    eps: float = 1.0e-10,
) -> pd.DataFrame:
    """Compute calendar, monotonicity, and butterfly penalties for call prices.

    C shape: (B,n_m,n_tau)
    """
    C = np.asarray(C, dtype=float)
    if C.ndim == 2:
        C = C[None, :, :]
    if C.ndim != 3:
        raise ValueError(f"C must be 2D or 3D, got {C.shape}")

    m_grid = np.asarray(m_grid, dtype=float)
    tau_grid = np.asarray(tau_grid, dtype=float)
    dm = np.diff(m_grid)
    dt = np.diff(tau_grid)

    if np.any(dm <= 0):
        raise ValueError("m_grid must be strictly increasing")
    if np.any(dt <= 0):
        raise ValueError("tau_grid/tenor grid must be strictly increasing")

    calendar = np.maximum(0.0, (C[:, :, :-1] - C[:, :, 1:]) / dt[None, None, :])
    mono = np.maximum(0.0, (C[:, 1:, :] - C[:, :-1, :]) / dm[None, :, None])

    left = (C[:, 1:-1, :] - C[:, :-2, :]) / dm[None, :-1, None]
    right = (C[:, 2:, :] - C[:, 1:-1, :]) / dm[None, 1:, None]
    butterfly = np.maximum(0.0, left - right)

    p_calendar = calendar.sum(axis=(1, 2))
    p_monotonicity = mono.sum(axis=(1, 2))
    p_butterfly = butterfly.sum(axis=(1, 2))
    phi = p_calendar + p_monotonicity + p_butterfly

    return pd.DataFrame(
        {
            "p_calendar": p_calendar,
            "p_monotonicity": p_monotonicity,
            "p_butterfly": p_butterfly,
            "phi": phi,
            "n_calendar_viol": (calendar > float(eps)).sum(axis=(1, 2)).astype(int),
            "n_monotonicity_viol": (mono > float(eps)).sum(axis=(1, 2)).astype(int),
            "n_butterfly_viol": (butterfly > float(eps)).sum(axis=(1, 2)).astype(int),
        }
    )


def arbitrage_penalties_from_iv_batch(
    sigma_frac: np.ndarray,
    m_grid: np.ndarray,
    tau_grid: np.ndarray,
    r: float = 0.0,
    eps: float = 1.0e-10,
) -> pd.DataFrame:
    C = relative_call_from_iv_batch(sigma_frac, m_grid=m_grid, tau_grid=tau_grid, r=r)
    return arbitrage_penalties_from_calls_batch(C, m_grid=m_grid, tau_grid=tau_grid, eps=eps)


def diagnose_paths(
    paths_frac: np.ndarray,
    m_grid: np.ndarray,
    tau_grid: np.ndarray,
    r: float = 0.0,
    surface_eps: float = 1.0e-10,
    chunk_size: int = 8192,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Return (path_diagnostics, surface_diagnostics).

    paths_frac shape: (n_paths,path_length,n_m,n_tau), IV in fraction units.
    path phi is sum_t Phi(sigma_t), as in the paper.
    """
    paths_frac = np.asarray(paths_frac, dtype=float)
    if paths_frac.ndim != 4:
        raise ValueError(f"Expected paths shape (n_paths,path_length,n_m,n_tau), got {paths_frac.shape}")

    n_paths, path_length, n_m, n_tau = paths_frac.shape
    flat = paths_frac.reshape(n_paths * path_length, n_m, n_tau)

    pieces = []
    for start in range(0, len(flat), int(chunk_size)):
        stop = min(start + int(chunk_size), len(flat))
        pieces.append(
            arbitrage_penalties_from_iv_batch(
                flat[start:stop],
                m_grid=m_grid,
                tau_grid=tau_grid,
                r=r,
                eps=surface_eps,
            )
        )
    surf_diag = pd.concat(pieces, ignore_index=True)
    surf_diag.insert(0, "surface_global_idx", np.arange(len(surf_diag), dtype=int))
    surf_diag.insert(1, "candidate_path_idx", np.repeat(np.arange(n_paths, dtype=int), path_length))
    surf_diag.insert(2, "step_idx", np.tile(np.arange(path_length, dtype=int), n_paths))

    grouped = surf_diag.groupby("candidate_path_idx", sort=True)
    path_diag = grouped.agg(
        path_phi=("phi", "sum"),
        mean_surface_phi=("phi", "mean"),
        median_surface_phi=("phi", "median"),
        max_surface_phi=("phi", "max"),
        p_calendar_sum=("p_calendar", "sum"),
        p_monotonicity_sum=("p_monotonicity", "sum"),
        p_butterfly_sum=("p_butterfly", "sum"),
        n_calendar_viol=("n_calendar_viol", "sum"),
        n_monotonicity_viol=("n_monotonicity_viol", "sum"),
        n_butterfly_viol=("n_butterfly_viol", "sum"),
    ).reset_index()
    zero_surface = grouped["phi"].apply(lambda x: float(np.mean(np.asarray(x) <= surface_eps)))
    path_diag["zero_surface_pct"] = path_diag["candidate_path_idx"].map(zero_surface) * 100.0
    path_diag["path_length"] = int(path_length)
    return path_diag, surf_diag


# PCA-on-daily-log-changes + AR(1) factor model P0
def fit_daily_change_pca_ar1(cube: np.ndarray, n_factors: int = 4, residual_covariance: str = "full") -> Dict[str, Any]:
    """Fit the data-driven factor model used as baseline P0.

    Steps:
      * Y_t = log sigma_t.
      * PCA/SVD is fitted to daily changes Delta Y_t.
      * Levels Y_t - mean(Y) are projected onto those eigensurfaces.
      * Each projection process is fitted as AR(1).
      * The residual covariance is estimated for multivariate innovations.
    """
    if residual_covariance not in {"full", "diag"}:
        raise ValueError("residual_covariance must be 'full' or 'diag'")

    batch = cube_to_batch_m_t(cube)
    output_in_percent = bool(np.nanmedian(batch) > 2.0)

    batch_frac = _to_fraction_vol(batch)
    batch_frac = _fill_nan_surface_batch(batch_frac)
    batch_frac = np.clip(batch_frac, 1.0e-8, None)

    n_dates, n_m, n_tau = batch_frac.shape
    if n_dates < 3:
        raise ValueError("Need at least 3 historical surfaces to fit PCA/AR(1).")

    Y = np.log(batch_frac).reshape(n_dates, n_m * n_tau)
    mean = Y.mean(axis=0)

    dY = np.diff(Y, axis=0)
    dY_mean = dY.mean(axis=0)
    dY_centered = dY - dY_mean[None, :]

    _, singular_values, Vt = np.linalg.svd(dY_centered, full_matrices=False)
    k = min(int(n_factors), Vt.shape[0])
    components = Vt[:k]

    scores = (Y - mean[None, :]) @ components.T

    mu = np.zeros(k, dtype=float)
    phi = np.zeros(k, dtype=float)
    intercept = np.zeros(k, dtype=float)
    residuals = np.zeros((n_dates - 1, k), dtype=float)

    for q in range(k):
        x0 = scores[:-1, q]
        x1 = scores[1:, q]
        if np.nanstd(scores[:, q]) < 1.0e-12:
            phi_q = 0.0
            intercept_q = float(np.nanmean(x1)) if len(x1) else 0.0
            mu_q = intercept_q
            resid_q = x1 - intercept_q
        else:
            A = np.column_stack([np.ones_like(x0), x0])
            intercept_q, phi_raw = np.linalg.lstsq(A, x1, rcond=None)[0]
            phi_q = float(np.clip(phi_raw, -0.995, 0.995))
            mu_q = float(intercept_q / (1.0 - phi_q)) if abs(1.0 - phi_q) > 1.0e-10 else float(np.mean(scores[:, q]))
            resid_q = x1 - (intercept_q + phi_q * x0)

        phi[q] = phi_q
        mu[q] = mu_q
        intercept[q] = intercept_q
        residuals[:, q] = resid_q

    if len(residuals) > 1:
        cov = np.cov(residuals, rowvar=False)
    else:
        cov = np.diag(np.var(residuals, axis=0))
    cov = np.atleast_2d(np.asarray(cov, dtype=float))
    if residual_covariance == "diag":
        cov = np.diag(np.diag(cov))

    # Numerical PSD repair for random sampling.
    cov = 0.5 * (cov + cov.T)
    eigval, eigvec = np.linalg.eigh(cov)
    eigval = np.maximum(eigval, 1.0e-14)
    cov = (eigvec * eigval[None, :]) @ eigvec.T

    total_var = float(np.sum(singular_values**2))
    explained = (singular_values[:k] ** 2) / max(total_var, 1.0e-14)

    return {
        "mean": mean,
        "components": components,
        "scores": scores,
        "mu": mu,
        "phi": phi,
        "intercept": intercept,
        "residual_cov": cov,
        "residual_covariance": residual_covariance,
        "shape": (n_m, n_tau),
        "output_in_percent": output_in_percent,
        "explained_variance_ratio": explained,
        "cumulative_explained_variance": np.cumsum(explained),
        "n_dates_fit": int(n_dates),
        "pca_on": "daily_log_iv_changes",
        "level_projection": "Y_t_minus_mean_on_daily_change_eigensurfaces",
    }


def _initial_scores(model: Dict[str, Any], cfg: SimulationConfig, rng: np.random.Generator, n_paths: int) -> np.ndarray:
    scores_hist = np.asarray(model["scores"], dtype=float)
    k = scores_hist.shape[1]

    if cfg.start_index is not None:
        idx = int(cfg.start_index)
        if idx < 0:
            idx = len(scores_hist) + idx
        if idx < 0 or idx >= len(scores_hist):
            raise ValueError(f"start_index out of range: {cfg.start_index}")
        return np.repeat(scores_hist[[idx]], n_paths, axis=0)

    mode = str(cfg.start_mode).lower()
    if mode == "last":
        return np.repeat(scores_hist[[-1]], n_paths, axis=0)
    if mode == "random_history":
        idxs = rng.integers(0, len(scores_hist), size=n_paths)
        return scores_hist[idxs].copy()
    if mode == "stationary":
        # Empirical stationary approximation from the historical score cloud.
        hist_mu = scores_hist.mean(axis=0)
        hist_cov = np.cov(scores_hist, rowvar=False)
        hist_cov = np.atleast_2d(hist_cov) + np.eye(k) * 1.0e-14
        return rng.multivariate_normal(hist_mu, hist_cov, size=n_paths)
    raise ValueError("start_mode must be one of: last, random_history, stationary")


def simulate_p0_factor_paths(model: Dict[str, Any], cfg: SimulationConfig) -> np.ndarray:
    """
    Simulate future candidate scenario paths from baseline model P0.
    The initial historical/reconstructed surface is used only as the starting state,
    not saved as output.
    """
    rng = np.random.default_rng(int(cfg.seed))

    n_paths = int(cfg.n_candidate_paths) if cfg.n_candidate_paths is not None else max(
        int(cfg.n_output_paths) * int(cfg.candidate_multiplier), 1000
    )
    path_length = int(cfg.path_length)

    if n_paths <= 0:
        raise ValueError("n_candidate_paths must be positive")
    if path_length <= 0:
        raise ValueError("path_length must be positive")

    components = np.asarray(model["components"], dtype=float)
    mean = np.asarray(model["mean"], dtype=float)
    mu = np.asarray(model["mu"], dtype=float)
    phi = np.asarray(model["phi"], dtype=float)
    cov = np.asarray(model["residual_cov"], dtype=float) * float(cfg.shock_scale) ** 2

    k = components.shape[0]
    current = _initial_scores(model, cfg, rng, n_paths)

    scores_paths = np.empty((n_paths, path_length, k), dtype=float)

    for t in range(path_length):
        eps = rng.multivariate_normal(np.zeros(k), cov, size=n_paths)
        current = mu[None, :] + phi[None, :] * (current - mu[None, :]) + eps
        scores_paths[:, t, :] = current

    Y = mean[None, None, :] + np.einsum("nlk,kd->nld", scores_paths, components)
    Y = np.clip(Y, np.log(float(cfg.vol_floor)), np.log(float(cfg.vol_cap)))

    paths = np.exp(Y).reshape((n_paths, path_length) + tuple(model["shape"]))
    return np.clip(paths, float(cfg.vol_floor), float(cfg.vol_cap))


# Weighted Monte Carlo on paths
def stable_exp_weights(phi: np.ndarray, beta: float) -> np.ndarray:
    phi = np.asarray(phi, dtype=float)
    if phi.ndim != 1:
        raise ValueError("phi must be one-dimensional")
    if len(phi) == 0:
        raise ValueError("phi is empty")

    logw = -float(beta) * phi
    logw = logw - np.nanmax(logw)
    weights = np.exp(logw)
    total = float(np.nansum(weights))
    if not np.isfinite(total) or total <= 0.0:
        out = np.zeros_like(phi, dtype=float)
        out[int(np.nanargmin(phi))] = 1.0
        return out
    return weights / total


def relative_entropy_to_uniform(weights: np.ndarray) -> float:
    weights = np.asarray(weights, dtype=float)
    positive = weights > 0
    n = len(weights)
    return float(np.sum(weights[positive] * np.log(weights[positive] * n)))


def effective_sample_size(weights: np.ndarray) -> float:
    weights = np.asarray(weights, dtype=float)
    return float(1.0 / np.sum(weights**2))


def select_paths_wmc(
    candidate_paths_frac: np.ndarray,
    candidate_path_diag: pd.DataFrame,
    cfg: SimulationConfig,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[str, Any]]:
    rng = np.random.default_rng(int(cfg.seed) + 271828)
    phi = candidate_path_diag["path_phi"].to_numpy(dtype=float)
    path_tol = float(cfg.path_arb_tol) if cfg.path_arb_tol is not None else float(cfg.surface_arb_tol) * int(cfg.path_length)

    if cfg.require_zero_path:
        eligible = np.where(phi <= path_tol)[0]
        if len(eligible) == 0:
            best = float(np.nanmin(phi))
            raise RuntimeError(
                "No zero-penalty path found in the candidate pool. "
                f"Best path_phi={best:.12g}, path_arb_tol={path_tol:.12g}. "
                "Increase --n-candidate-paths, reduce --shock-scale, or use finite beta."
            )
        weights = np.zeros_like(phi, dtype=float)
        weights[eligible] = 1.0 / len(eligible)
        selection_mode = "beta_infinity_uniform_over_zero_penalty_paths"
    else:
        weights = stable_exp_weights(phi, beta=float(cfg.beta))
        selection_mode = "finite_beta_path_weighted_monte_carlo"

    selected_idx = rng.choice(
        len(candidate_paths_frac),
        size=int(cfg.n_output_paths),
        replace=True,
        p=weights,
    )
    meta = {
        "selection_mode": selection_mode,
        "beta": float(cfg.beta),
        "require_zero_path": bool(cfg.require_zero_path),
        "path_arb_tol": path_tol,
        "n_candidate_paths": int(len(candidate_paths_frac)),
        "n_zero_penalty_paths": int((phi <= path_tol).sum()),
        "candidate_path_phi_min": float(np.nanmin(phi)),
        "candidate_path_phi_median": float(np.nanmedian(phi)),
        "candidate_path_phi_mean": float(np.nanmean(phi)),
        "candidate_path_phi_max": float(np.nanmax(phi)),
        "wmc_effective_sample_size": effective_sample_size(weights),
        "wmc_effective_sample_size_pct": 100.0 * effective_sample_size(weights) / len(weights),
        "wmc_relative_entropy_to_uniform": relative_entropy_to_uniform(weights),
    }
    return candidate_paths_frac[selected_idx], selected_idx.astype(int), weights, meta


def _total_candidate_paths(cfg: SimulationConfig) -> int:
    return int(cfg.n_candidate_paths) if cfg.n_candidate_paths is not None else max(
        int(cfg.n_output_paths) * int(cfg.candidate_multiplier), 1000
    )


def _candidate_batch_ranges(n_total: int, batch_size: int):
    batch_size = max(1, int(batch_size))
    for start in range(0, int(n_total), batch_size):
        stop = min(start + batch_size, int(n_total))
        yield start, stop


def _seed_for_candidate_batch(base_seed: int, batch_start: int) -> int:
    # Deterministic and independent of machine/platform. 2**32-1 keeps NumPy happy.
    return int((int(base_seed) + 1000003 * int(batch_start) + 9176) % (2**32 - 1))


def _config_for_candidate_batch(cfg: SimulationConfig, batch_start: int, batch_n: int) -> SimulationConfig:
    return replace(
        cfg,
        n_candidate_paths=int(batch_n),
        seed=_seed_for_candidate_batch(int(cfg.seed), int(batch_start)),
    )

def diagnose_candidate_paths_streaming(
    model: Dict[str, Any],
    cfg: SimulationConfig,
    m_grid: np.ndarray,
    tau_grid: np.ndarray,
) -> pd.DataFrame:
    n_total = _total_candidate_paths(cfg)
    pieces = []
    for start, stop in _candidate_batch_ranges(n_total, int(cfg.candidate_batch_size)):
        batch_cfg = _config_for_candidate_batch(cfg, start, stop - start)
        batch_paths_frac = simulate_p0_factor_paths(model, batch_cfg)
        batch_path_diag, _ = diagnose_paths(
            batch_paths_frac,
            m_grid=m_grid,
            tau_grid=tau_grid,
            r=float(cfg.r),
            surface_eps=float(cfg.surface_arb_tol),
        )
        batch_path_diag = batch_path_diag.copy()
        batch_path_diag["candidate_path_idx"] = batch_path_diag["candidate_path_idx"].astype(int) + int(start)
        batch_path_diag["candidate_batch_start"] = int(start)
        batch_path_diag["candidate_batch_stop"] = int(stop)
        pieces.append(batch_path_diag)
        del batch_paths_frac

    if not pieces:
        raise RuntimeError("No candidate paths were generated.")
    candidate_path_diag = pd.concat(pieces, ignore_index=True)
    candidate_path_diag = candidate_path_diag.sort_values("candidate_path_idx").reset_index(drop=True)
    expected = np.arange(n_total, dtype=int)
    got = candidate_path_diag["candidate_path_idx"].to_numpy(dtype=int)
    if len(got) != n_total or not np.array_equal(got, expected):
        raise RuntimeError("Internal error: candidate diagnostics are not contiguous/sorted.")
    return candidate_path_diag


def select_path_indices_wmc(
    candidate_path_diag: pd.DataFrame,
    cfg: SimulationConfig,
) -> Tuple[np.ndarray, np.ndarray, Dict[str, Any]]:
    rng = np.random.default_rng(int(cfg.seed) + 271828)
    phi = candidate_path_diag["path_phi"].to_numpy(dtype=float)
    path_tol = float(cfg.path_arb_tol) if cfg.path_arb_tol is not None else float(cfg.surface_arb_tol) * int(cfg.path_length)

    if cfg.require_zero_path:
        eligible = np.where(phi <= path_tol)[0]
        if len(eligible) == 0:
            best = float(np.nanmin(phi))
            raise RuntimeError(
                "No zero-penalty path found in the candidate pool. "
                f"Best path_phi={best:.12g}, path_arb_tol={path_tol:.12g}. "
                "Increase --n-candidate-paths, increase --path-arb-tol, reduce --shock-scale, "
                "or use finite beta by removing --require-zero-path."
            )
        weights = np.zeros_like(phi, dtype=float)
        weights[eligible] = 1.0 / len(eligible)
        selection_mode = "beta_infinity_uniform_over_zero_penalty_paths"
    else:
        weights = stable_exp_weights(phi, beta=float(cfg.beta))
        selection_mode = "finite_beta_path_weighted_monte_carlo"

    selected_idx = rng.choice(
        len(phi),
        size=int(cfg.n_output_paths),
        replace=True,
        p=weights,
    ).astype(int)

    meta = {
        "selection_mode": selection_mode,
        "beta": float(cfg.beta),
        "require_zero_path": bool(cfg.require_zero_path),
        "path_arb_tol": path_tol,
        "n_candidate_paths": int(len(phi)),
        "candidate_batch_size": int(cfg.candidate_batch_size),
        "n_zero_penalty_paths": int((phi <= path_tol).sum()),
        "candidate_path_phi_min": float(np.nanmin(phi)),
        "candidate_path_phi_median": float(np.nanmedian(phi)),
        "candidate_path_phi_mean": float(np.nanmean(phi)),
        "candidate_path_phi_max": float(np.nanmax(phi)),
        "wmc_effective_sample_size": effective_sample_size(weights),
        "wmc_effective_sample_size_pct": 100.0 * effective_sample_size(weights) / len(weights),
        "wmc_relative_entropy_to_uniform": relative_entropy_to_uniform(weights),
    }
    return selected_idx, weights, meta


def regenerate_selected_paths(
    model: Dict[str, Any],
    cfg: SimulationConfig,
    selected_candidate_idx: np.ndarray,
) -> np.ndarray:
    selected_candidate_idx = np.asarray(selected_candidate_idx, dtype=int)
    n_total = _total_candidate_paths(cfg)
    positions_by_candidate: Dict[int, list[int]] = defaultdict(list)
    for out_pos, candidate_id in enumerate(selected_candidate_idx.tolist()):
        if candidate_id < 0 or candidate_id >= n_total:
            raise ValueError(f"selected candidate id out of range: {candidate_id}")
        positions_by_candidate[int(candidate_id)].append(int(out_pos))

    selected_paths_frac: Optional[np.ndarray] = None
    needed_ids = set(positions_by_candidate.keys())

    for start, stop in _candidate_batch_ranges(n_total, int(cfg.candidate_batch_size)):
        ids_in_batch = [cid for cid in needed_ids if start <= cid < stop]
        if not ids_in_batch:
            continue
        batch_cfg = _config_for_candidate_batch(cfg, start, stop - start)
        batch_paths_frac = simulate_p0_factor_paths(model, batch_cfg)
        if selected_paths_frac is None:
            selected_paths_frac = np.empty(
                (len(selected_candidate_idx),) + batch_paths_frac.shape[1:],
                dtype=batch_paths_frac.dtype,
            )
        for cid in ids_in_batch:
            local = int(cid - start)
            for out_pos in positions_by_candidate[cid]:
                selected_paths_frac[out_pos] = batch_paths_frac[local]
        del batch_paths_frac

    if selected_paths_frac is None:
        raise RuntimeError("No selected paths could be regenerated.")
    return selected_paths_frac


def simulate_arbitrage_free_paths(config: SimulationConfig) -> SimulationResult:
    cube, m_grid, tenor_days, asof_dates_input, input_meta = load_cube_npz(config.input_path)
    tau_grid = np.asarray(tenor_days, dtype=float) / 365.0
    output_in_percent = bool(np.nanmedian(cube) > 2.0)

    model = fit_daily_change_pca_ar1(
        cube,
        n_factors=int(config.n_factors),
        residual_covariance=str(config.residual_covariance),
    )

  
    candidate_path_diag = diagnose_candidate_paths_streaming(
        model,
        config,
        m_grid=m_grid,
        tau_grid=tau_grid,
    )

    selected_candidate_idx, weights, wmc_meta = select_path_indices_wmc(
        candidate_path_diag,
        config,
    )

    selected_paths_frac = regenerate_selected_paths(
        model,
        config,
        selected_candidate_idx,
    )

    selected_path_diag, selected_surface_diag = diagnose_paths(
        selected_paths_frac,
        m_grid=m_grid,
        tau_grid=tau_grid,
        r=float(config.r),
        surface_eps=float(config.surface_arb_tol),
    )
    selected_path_diag.insert(0, "output_path_idx", np.arange(len(selected_path_diag), dtype=int))
    selected_path_diag.insert(1, "selected_candidate_path_idx", selected_candidate_idx)
    selected_path_diag["candidate_weight"] = weights[selected_candidate_idx]

    selected_surface_diag = selected_surface_diag.rename(columns={"candidate_path_idx": "output_path_idx"})
    selected_surface_diag.insert(
        2,
        "selected_candidate_path_idx",
        np.repeat(selected_candidate_idx, int(config.path_length)),
    )

    candidate_path_diag = candidate_path_diag.copy()
    candidate_path_diag["wmc_weight"] = weights
    candidate_path_diag["rank_by_path_phi"] = candidate_path_diag["path_phi"].rank(method="first")

    selected_paths = _from_fraction_vol(selected_paths_frac, output_in_percent=output_in_percent)
    flat_selected = selected_paths.reshape(
        int(config.n_output_paths) * int(config.path_length),
        selected_paths.shape[2],
        selected_paths.shape[3],
    )
    out_cube = batch_m_t_to_cube(flat_selected)

    out_dates = np.array(
        [
            f"path_{p:04d}_t_{t:04d}"
            for p in range(int(config.n_output_paths))
            for t in range(int(config.path_length))
        ],
        dtype="U32",
    )

    meta = {
        "method": "cont_vuletic_path_weighted_monte_carlo_streaming",
        "input_path": str(config.input_path),
        "input_meta": input_meta,
        "n_input_dates": int(cube.shape[2]),
        "n_output_paths": int(config.n_output_paths),
        "path_length": int(config.path_length),
        "n_factors": int(config.n_factors),
        "pca_on": model["pca_on"],
        "level_projection": model["level_projection"],
        "explained_variance_ratio": np.asarray(model["explained_variance_ratio"], dtype=float),
        "cumulative_explained_variance": np.asarray(model["cumulative_explained_variance"], dtype=float),
        "ar_phi": np.asarray(model["phi"], dtype=float),
        "ar_mu": np.asarray(model["mu"], dtype=float),
        "residual_covariance": str(model["residual_covariance"]),
        "start_mode": str(config.start_mode),
        "start_index": config.start_index,
        "shock_scale": float(config.shock_scale),
        "output_in_percent": bool(output_in_percent),
        "surface_arb_tol": float(config.surface_arb_tol),
        **wmc_meta,
        "selected_path_phi_max": float(selected_path_diag["path_phi"].max()),
        "selected_path_phi_mean": float(selected_path_diag["path_phi"].mean()),
        "selected_surface_phi_max": float(selected_surface_diag["phi"].max()),
        "selected_zero_surface_pct": float(100.0 * np.mean(selected_surface_diag["phi"].to_numpy() <= float(config.surface_arb_tol))),
    }

    return SimulationResult(
        paths=selected_paths,
        cube=out_cube,
        m_grid=np.asarray(m_grid, dtype=float),
        tenor_days=np.asarray(tenor_days, dtype=float),
        asof_dates=out_dates,
        selected_candidate_path_indices=selected_candidate_idx,
        candidate_path_diagnostics=candidate_path_diag,
        selected_path_diagnostics=selected_path_diag,
        selected_surface_diagnostics=selected_surface_diag,
        meta=meta,
    )


def main() -> None:
    import argparse

    p = argparse.ArgumentParser(
        "cont_vuletic_wmc_paths: path-level Weighted Monte Carlo IV surface simulation"
    )
    p.add_argument("--input", default="data/treated/vol_surface_cube.npz", help="Input treated cube .npz")
    p.add_argument("--out", default="data/treated/simulated_vol_surface.npz", help="Output .npz")
    p.add_argument("--candidate-path-diagnostics", default="data/treated/wmc_candidate_path_diagnostics.csv")
    p.add_argument("--selected-path-diagnostics", default="data/treated/wmc_selected_path_diagnostics.csv")
    p.add_argument("--selected-surface-diagnostics", default="data/treated/wmc_selected_surface_diagnostics.csv")

    p.add_argument("--n-output-paths", type=int, default=10)
    p.add_argument("--path-length", type=int, default=64, help="Number of surfaces per path, including t=0")
    p.add_argument("--n-candidate-paths", type=int, default=None)
    p.add_argument("--candidate-multiplier", type=int, default=500)
    p.add_argument("--candidate-batch-size", type=int, default=512, help="Number of candidate paths generated per batch; lower this if macOS kills the process")
    p.add_argument("--n-factors", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--beta", type=float, default=1.0e4)
    p.add_argument("--shock-scale", type=float, default=1.0)
    p.add_argument("--require-zero-path", action="store_true", help="Use beta=infinity style rejection at path level")
    p.add_argument("--surface-arb-tol", type=float, default=1.0e-10)
    p.add_argument("--path-arb-tol", type=float, default=None)
    p.add_argument("--start-mode", choices=["last", "random_history", "stationary"], default="last")
    p.add_argument("--start-index", type=int, default=None)
    p.add_argument("--residual-covariance", choices=["full", "diag"], default="full")
    p.add_argument("--r", type=float, default=0.0)
    p.add_argument("--vol-floor", type=float, default=1.0e-6)
    p.add_argument("--vol-cap", type=float, default=5.0)

    args = p.parse_args()

    cfg = SimulationConfig(
        input_path=Path(args.input),
        output_path=Path(args.out),
        candidate_path_diagnostics_path=Path(args.candidate_path_diagnostics),
        selected_path_diagnostics_path=Path(args.selected_path_diagnostics),
        selected_surface_diagnostics_path=Path(args.selected_surface_diagnostics),
        n_output_paths=args.n_output_paths,
        path_length=args.path_length,
        n_candidate_paths=args.n_candidate_paths,
        candidate_multiplier=args.candidate_multiplier,
        candidate_batch_size=args.candidate_batch_size,
        n_factors=args.n_factors,
        seed=args.seed,
        beta=args.beta,
        shock_scale=args.shock_scale,
        require_zero_path=args.require_zero_path,
        surface_arb_tol=args.surface_arb_tol,
        path_arb_tol=args.path_arb_tol,
        start_mode=args.start_mode,
        start_index=args.start_index,
        residual_covariance=args.residual_covariance,
        r=args.r,
        vol_floor=args.vol_floor,
        vol_cap=args.vol_cap,
    )

    result = simulate_arbitrage_free_paths(cfg)
    save_result_npz(cfg.output_path, result)

    cfg.candidate_path_diagnostics_path.parent.mkdir(parents=True, exist_ok=True)
    result.candidate_path_diagnostics.to_csv(cfg.candidate_path_diagnostics_path, index=False)
    result.selected_path_diagnostics.to_csv(cfg.selected_path_diagnostics_path, index=False)
    result.selected_surface_diagnostics.to_csv(cfg.selected_surface_diagnostics_path, index=False)

    print(f"Saved output paths/cube to {cfg.output_path}")
    print(f"Saved candidate path diagnostics to {cfg.candidate_path_diagnostics_path}")
    print(f"Saved selected path diagnostics to {cfg.selected_path_diagnostics_path}")
    print(f"Saved selected surface diagnostics to {cfg.selected_surface_diagnostics_path}")
    print(f"paths shape: {result.paths.shape}")
    print(f"cube shape: {result.cube.shape}")
    print("candidate path phi min/median/max:",
          result.meta["candidate_path_phi_min"],
          result.meta["candidate_path_phi_median"],
          result.meta["candidate_path_phi_max"])
    print(f"WMC ESS: {result.meta['wmc_effective_sample_size']:.2f} "
          f"({result.meta['wmc_effective_sample_size_pct']:.2f}%)")
    print(f"selected max path phi: {result.meta['selected_path_phi_max']:.12g}")
    print(f"selected max surface phi: {result.meta['selected_surface_phi_max']:.12g}")
    print("explained variance ratio:", result.meta["explained_variance_ratio"])


if __name__ == "__main__":
    main()
